server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bill-service
          uri: lb://bill-service
          predicates:
            - Path=/api/v1/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/v1/**
        - id: pay-mode-service
          uri: lb://pay-mode-service
          predicates:
            - Path=/api/v1/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/**