server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/GMaikerYactayo/microservice-facturation
          search-paths: config-data
  application:
    name: config-service
